### PR TITLE
Add missing g++ dep to server build (Fixes #110)

### LINKED ISSUE #110: Error while installing pip requirements in final_image_preparation.sh - missing g++
When running:

```
$ docker build --platform linux/amd64 -t clearml-server:1.2.0 -f docker/build/Dockerfile .
```

I get the following error:

```
...
#13 293.3 Installing collected packages: attrs, pycparser, cffi, bcrypt, jmespath, docutils, python-dateutil, urllib3, botocore, s3transfer, boto3, dpath, certifi, elasticsearch, fastjsonschema, funcsigs, orderedmultidict, furl, gunicorn, humanfriendly, jinja2, jsonmodels, pyrsistent, jsonschema, ply, luqum, dnspython, pymongo, mongoengine, nested-dict, packaging, psutil, pyjwt, python-rapidjson, redis, redis-py-cluster, PyYAML, future, related, idna, charset-normalizer, requests, semantic-version, tqdm, decorator, validators
#13 298.6   Running setup.py install for dpath: started
#13 300.2     Running setup.py install for dpath: finished with status 'done'
#13 301.6   Found existing installation: Jinja2 3.0.3
#13 301.7     Uninstalling Jinja2-3.0.3:
#13 301.7       Successfully uninstalled Jinja2-3.0.3
#13 302.1   Running setup.py install for jsonmodels: started
#13 303.7     Running setup.py install for jsonmodels: finished with status 'done'
#13 306.2   Running setup.py install for nested-dict: started
#13 307.8     Running setup.py install for nested-dict: finished with status 'done'
#13 308.0   Running setup.py install for psutil: started
#13 317.0     Running setup.py install for psutil: finished with status 'done'
#13 317.2   Running setup.py install for python-rapidjson: started
#13 318.6     Running setup.py install for python-rapidjson: finished with status 'error'
#13 318.6     Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-y_pqitge/python-rapidjson/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k1o7f8pl-record/install-record.txt --single-version-externally-managed --compile:
#13 318.6     running install
#13 318.6     running build
#13 318.6     running build_ext
#13 318.6     building 'rapidjson' extension
#13 318.6     creating build
#13 318.6     creating build/temp.linux-x86_64-3.6
#13 318.6     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPYTHON_RAPIDJSON_VERSION=1.6 -DRAPIDJSON_EXACT_VERSION=v1.1.0-677-g4d6cb081 -I./rapidjson/include -I/usr/include/python3.6m -c ./rapidjson.cpp -o build/temp.linux-x86_64-3.6/./rapidjson.o -pedantic -Wno-long-long -Wno-write-strings
#13 318.6     gcc: error trying to exec 'cc1plus': execvp: No such file or directory
#13 318.6     error: command 'gcc' failed with exit status 1
#13 318.6
#13 318.6     ----------------------------------------
#13 318.9 Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-y_pqitge/python-rapidjson/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k1o7f8pl-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-y_pqitge/python-rapidjson/
------
executor failed running [/bin/sh -c /bin/bash -c '/tmp/internal_files/final_image_preparation.sh']: exit code: 1
```

### PR DESCRIPTION
**Pull request by reuben**

### CODE REVIEW

**Comment by jkhenning** [comment]
Hi @reuben ,

Do you have some info on how this happens? I can't figure out why I haven't seen this issue 🙁

**Comment by jkhenning** [comment]
Sorry, just saw the issue - I guess this is due to a new rapidjson version maybe?

**Comment by reuben** [comment]
Could be, I didn't try to track down when it started happening.

**Comment by jkhenning** [comment]
OK, thanks 🙂

**Pull request merged**
