### PR TITLE
Fix default value of CLEARML_AGENT_UPDATE_VERSION for agent-services

### PR DESCRIPTION
**Pull request by mmiller-max**
Cf #113

### CODE REVIEW

**Comment by jkhenning** [comment]
Hi @mmiller-max , tracking down that line of code, it seems the origin was with a bug report stating that without the `"`, this doesn't work on MacOS...

**Comment by mmiller-max** [comment]
I can try and test that and see if there is a solution for both

**Comment by mmiller-max** [comment]
I get the same error on MacOS without the change:

```
clearml-agent-services | ERROR: Invalid requirement: 'clearml-agent">=0.17.0"'
```

Interestingly it works with both of these:
```
CLEARML_AGENT_UPDATE_VERSION: ${CLEARML_AGENT_UPDATE_VERSION:->="0.17.0"}
```
```
CLEARML_AGENT_UPDATE_VERSION: ${CLEARML_AGENT_UPDATE_VERSION:->=0.17.0}
```

**Comment by mmiller-max** [comment]
@jkhenning just wondering what the way forward with this should be? Is it possible to validate elsewhere that the proposed solution does work on MacOS?

**Comment by jkhenning** [comment]
@mmiller-max I'll find someone with a MacOS and have them test it 🙂

**Comment by mmiller-max** [comment]
Hey @jkhenning, just wondering if you'd had a chance to find someone to test on a Mac?

**Comment by jkhenning** [comment]
Hi @mmiller-max, not yet 🙁 - perhaps we can find someone in the community who might assist with this?

**Comment by mmiller-max** [comment]
I've tested on MacOS (M1, Big Sur) and I get the same error as on the linux server (see [message above](https://github.com/allegroai/clearml-server/pull/114#issuecomment-1056903970)). I can put a message on Slack to get some additional tests?

What would be enough of a test to be happy this works, running `docker-compose -f docker/docker-compose.yml up` on an Intel Mac, without `CLEARML_AGENT_UPDATE_VERSION` set and checking the agent-services starts?

**Comment by jkhenning** [comment]
> I can put a message on Slack to get some additional tests?

Yes, of course!

> What would be enough of a test to be happy this works, running docker-compose -f docker/docker-compose.yml up on an Intel Mac, without CLEARML_AGENT_UPDATE_VERSION set and checking the agent-services starts?

Yeah, I think that's a reasonable test 🙂

**Comment by mmiller-max** [comment]
I do have an intel Mac I can test this on now, so will aim to do this tomorrow.

**Comment by mmiller-max** [comment]
@jkhenning just bumping this :)

**Comment by jkhenning** [comment]
@mmiller-max sorry for the delay! I agree, I'll merge :)

**Comment by mmiller-max** [comment]
No worries at all! Thanks 👍

**Pull request merged**
